'''

Project Brief
What’s the temperature in the Rovaniemi right now?

Let’s find it out with Python.

Your task for this project is to create a Python program that gets any city name as input and outputs the current temperature for that city.

Expected Output
When the program is executed, the terminal asks the user to enter a city. Once the user enters the city, the program outputs the temperature of that city as shown in the demo below.


👉 Pro tip: You can verify if the temperature generated by your program is the same as the temperature shown in this live webcam of the city of Rovaniemi in Finland.



'''