'''
Project Description
    This project uses the versatile Beautiful Soup webscraping Python library to fetch real-time news headlines from a news website and 
    stores them in a CSV file for easy access.
    We are scraping the current headlines from the Aljazeera website.
    Here is the file generated by the program.

Prerequisites
Required Libraries: requests, BeautifulSoup, pandas
pip install requests beautifulsoup4 pandas
'''

